/*
defines a function that changes the URL of the current page to include a query parameter, 
which triggers a re-rendering of the page with devices classified according to the selected criterion (e.g., room, category, or activeness).
Generated by ChatGPT 4o

@author https://chat.openai.com/
*/
function filterDevices(classifyBy) {
    window.location.href = `/roomList?classifyBy=${classifyBy}`;
}
